apiVersion: v1
kind: Service
metadata:
  name: backend-app-eu
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: backend-app
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: 8080