apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: ingress-jwt
  namespace: demo
spec:
  selector:
    matchLabels:
      asm: ingressgateway
  jwtRules:
  - issuer: "demo-claim@secure.gcp.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.17/security/tools/jwt/samples/jwks.json"